commit_message: '[skip ci]'
files:
  - source: /DevBin/Localization/*.resx
    translation: /DevBin/Resources/%file_name%.%locale%.%file_extension%
  - source: /DevBin/Localization/Pages/*.resx
    translation: /DevBin/Resources/Pages/%file_name%.%locale%.%file_extension%
  - source: /DevBin/Localization/Pages/User/*.resx
    translation: /DevBin/Resources/Pages/User/%file_name%.%locale%.%file_extension%
