commit_message: '[skip ci]'
files:
  - source: /DevBin/Localization/*.resx
    translation: /DevBin/Resources/%file_name%.%two_letters_code%.%file_extension%
  - source: /DevBin/Localization/Pages/*.resx
    translation: /DevBin/Resources/Pages/%file_name%.%two_letters_code%.%file_extension%
  - source: /DevBin/Localization/Pages/User/*.resx
    translation: /DevBin/Resources/Pages/User/%file_name%.%two_letters_code%.%file_extension%
  - source: /DevBin/Localization/Areas/Identity/Pages/Account/*.resx
    translation: /DevBin/Resources/Areas/Identity/Pages/Account/%file_name%.%two_letters_code%.%file_extension%
  - source: /DevBin/Localization/Areas/Identity/Pages/Account/Manage/*.resx
    translation: /DevBin/Resources/Areas/Identity/Pages/Account/Manage/%file_name%.%two_letters_code%.%file_extension%
