//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBin.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Shared {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Shared() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DevBin.Localization._Shared", typeof(_Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Exposure {
            get {
                return ResourceManager.GetString("Exposure", resourceCulture);
            }
        }
        
        internal static string Exposures {
            get {
                return ResourceManager.GetString("Exposures", resourceCulture);
            }
        }
        
        internal static string Exposure_Private {
            get {
                return ResourceManager.GetString("Exposure.Private", resourceCulture);
            }
        }
        
        internal static string Exposure_Unlisted {
            get {
                return ResourceManager.GetString("Exposure.Unlisted", resourceCulture);
            }
        }
        
        internal static string Exposure_Public {
            get {
                return ResourceManager.GetString("Exposure.Public", resourceCulture);
            }
        }
        
        internal static string DevBin {
            get {
                return ResourceManager.GetString("DevBin", resourceCulture);
            }
        }
        
        internal static string _dev {
            get {
                return ResourceManager.GetString(".dev", resourceCulture);
            }
        }
        
        internal static string NativeLanguageName {
            get {
                return ResourceManager.GetString("NativeLanguageName", resourceCulture);
            }
        }
        
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        internal static string NavBar_Guest_Login {
            get {
                return ResourceManager.GetString("NavBar.Guest.Login", resourceCulture);
            }
        }
        
        internal static string NavBar_Guest_SignUp {
            get {
                return ResourceManager.GetString("NavBar.Guest.SignUp", resourceCulture);
            }
        }
        
        internal static string NavBar_JSRequired {
            get {
                return ResourceManager.GetString("NavBar.JSRequired", resourceCulture);
            }
        }
        
        internal static string NavBar_LatestPastes {
            get {
                return ResourceManager.GetString("NavBar.LatestPastes", resourceCulture);
            }
        }
        
        internal static string NavBar_NewPaste {
            get {
                return ResourceManager.GetString("NavBar.NewPaste", resourceCulture);
            }
        }
        
        internal static string NavBar_Reports {
            get {
                return ResourceManager.GetString("NavBar.Reports", resourceCulture);
            }
        }
        
        internal static string NavBar_Search {
            get {
                return ResourceManager.GetString("NavBar.Search", resourceCulture);
            }
        }
        
        internal static string NavBar_User_Logout {
            get {
                return ResourceManager.GetString("NavBar.User.Logout", resourceCulture);
            }
        }
        
        internal static string NavBar_User_Settings {
            get {
                return ResourceManager.GetString("NavBar.User.Settings", resourceCulture);
            }
        }
        
        internal static string NavBar_User_YourPastes {
            get {
                return ResourceManager.GetString("NavBar.User.YourPastes", resourceCulture);
            }
        }
        
        internal static string Footer_AdCraftOS_PC {
            get {
                return ResourceManager.GetString("Footer.AdCraftOS-PC", resourceCulture);
            }
        }
        
        internal static string Footer_DeveloperDocs {
            get {
                return ResourceManager.GetString("Footer.DeveloperDocs", resourceCulture);
            }
        }
        
        internal static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer.PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string Footer_ToS {
            get {
                return ResourceManager.GetString("Footer.ToS", resourceCulture);
            }
        }
    }
}
